CREATE TABLE FILMES (
	ID_FILME SERIAL PRIMARY KEY,
	NOME_FILME VARCHAR(100) NOT NULL,
	DATA_LANCAMENTO DATE,
	DURACAO_MINUTOS INTEGER NOT NULL
);

CREATE TABLE FUNCIONARIOS (
	ID_FUNCIONARIO SERIAL PRIMARY KEY,
	NOME_FUNCIONARIO VARCHAR(100),
	FUNCAO VARCHAR(100),
	TELEFONE VARCHAR(15),
	EMAIL VARCHAR(254)
);